import { labs as zhLabs, lessons as zhLessons, type Lab, type Lesson, type LessonSection } from "./course";

const p00Sections: LessonSection[] = [
  { id: "runtime-map", eyebrow: "Step 1 · Run it", title: "How do TypeScript, JavaScript, Node.js, and browsers fit together?", paragraphs: ["Think of JavaScript as a recipe. A browser and Node.js are two kitchens that can follow it: browsers are good at web pages, while Node.js is good at files and servers.", "TypeScript is a proofreader beside you while you write. It spots suspicious values before the program runs. The type notes are removed afterward, and the browser or Node.js receives ordinary JavaScript. Predict the output, run it, then change message to 42 and read the warning."], code: zhLessons[0].sections[0].code, callout: { tone: "runtime", title: "Remember one sentence", body: "TypeScript warns you before execution; JavaScript is what actually runs." } },
  { id: "values", eyebrow: "Step 2 · Name your data", title: "Meet the five values you will see most often", paragraphs: ["Programs spend most of their time storing and changing data. \"CodePilot\" is text, 1 is a number, and true is a yes/no value. null usually means “deliberately empty”; undefined usually means “not provided yet.”", "const means the name will not be assigned a different value; let means it may change. Predict the five outputs, run the code, then replace count += 1 with count = \"two\" and read the diagnostic."], code: zhLessons[0].sections[1].code },
  { id: "collections", eyebrow: "Step 3 · Build a task", title: "An object is a task card; an array is a stack of cards", paragraphs: ["A review task has a title, tags, and perhaps an assignee. An object groups those related fields; an array stores a list of items. task.title reads the title field.", "The ? after assignee means the field may be missing. The ?. only continues when an assignee exists. Predict the output, remove ?., and inspect the warning. Then complete the first Playground."], code: zhLessons[0].sections[2].code },
  { id: "functions", eyebrow: "Step 4 · Reuse an action", title: "A function is a small machine with an input and an output", paragraphs: ["Put a title into format and it returns uppercase text. title: string says the input must be text; the : string after the parentheses says the output is text too. An arrow function is simply a shorter function syntax.", "renderAll also receives a function to call later—a callback. Predict the array, then change format's output type to number. Read the error as: what did I provide, and what was required?"], code: zhLessons[0].sections[3].code },
  { id: "type-language", eyebrow: "Step 5 · Limit the choices", title: "Not every string is a valid status", paragraphs: ["The editor can infer that inferred is a string from its value. You do not need to label every local variable; add annotations where the rule is not obvious.", "The | symbol means “one of these choices.” Priority allows only 1, 2, or 3. A task status should allow todo, reviewing, done, or blocked—not any typo. The second Playground makes that difference visible."], code: zhLessons[0].sections[4].code },
  { id: "aliases-interfaces", eyebrow: "Step 6 · Name a rule", title: "You do not need to choose between type and interface yet", paragraphs: ["Long rules are easier to read when named. type TaskStatus names a set of choices. interface ReviewResult lists the fields a result must contain. extends adds fields to an existing object shape.", "A useful beginner rule: use type for a fixed list of choices and interface for an object form. Run the code, remove summary, and see how the editor reports the missing field."], code: zhLessons[0].sections[5].code },
  { id: "unknown-any", eyebrow: "Step 7 · Open external data safely", title: "If you do not know what a value is, do not pretend", paragraphs: ["Network responses, user input, and JSON files are unopened packages. any closes your eyes and disables useful checking. unknown honestly says “I do not know yet,” so you must inspect the package first.", "Use unknown at boundaries. In the third Playground, do not erase the warning with any. Use typeof and property checks to prove that title really is a string."], code: zhLessons[0].sections[6].code, callout: { tone: "boundary", title: "The red underline saves debugging time", body: "Read the first error: what value did the code provide, and what did this location require? Fix one thing, then check again." } },
  { id: "erasure", eyebrow: "Final step · Know the boundary", title: "Type labels are gone when the program runs", paragraphs: ["Remember the proofreader? After checking, ReviewTask and : string are removed, leaving JavaScript. Types catch source-code mistakes, but they cannot inspect a real network response for you.", "You can now read the basic code used later: M00 asks how to judge AI code, M01 explains how JavaScript behaves, and M02 handles work that finishes later."], code: zhLessons[0].sections[7].code, callout: { tone: "static", title: "Types are not runtime bodyguards", body: "Types help while writing and compiling. Real data from a network, JSON, storage, or AI still needs runtime checks." } },
];

const translatedSections: Record<Lesson["id"], LessonSection[]> = {
  P00: p00Sections,
  M00: [
    { id: "compile-is-not-proof", eyebrow: "A real failure", title: "Why can a program crash when the editor shows no errors?", paragraphs: ["TypeScript checks information visible in source code. Network responses, environment variables, database rows, and AI output only arrive while the program runs. A type name cannot repair bad data.", "as ReviewInput only asks the editor to trust you. If code is actually a number, the next line still crashes. Predict the failure, then validate the input in the Playground."], code: zhLessons[1].sections[0].code, callout: { tone: "failure", title: "as is a promise, not a check", body: "Treat data from outside your program as unknown until you inspect it." } },
    { id: "five-layers", eyebrow: "Mental model", title: "Code passes five gates before a user relies on it", paragraphs: ["The editor gives quick hints, tsc checks the project, a build tool produces JavaScript, the runtime handles real input, and tests try to break the behavior. Passing one gate does not replace the others."], bullets: ["Editor: fast feedback, not the final judge", "Type checker: rules out some mistakes without running code", "Build: creates output and may not type-check", "Runtime: decides what really happens", "Tests and logs: provide evidence about behavior"], callout: { tone: "static", title: "A common Vite boundary", body: "Vite transpiles TypeScript but does not replace a separate project-wide tsc check." } },
    { id: "trust-review", eyebrow: "Review method", title: "Use five questions instead of “looks fine”", paragraphs: ["TRUST is a checklist: Are inputs and outputs clear? Is external data checked? What happens on failure? Could files or secrets be harmed? Would a test catch the bug?"], bullets: ["Types & contracts: can an invalid state still be created?", "Runtime boundaries: was external data actually parsed?", "Unhappy paths: what happens on timeout or cancellation?", "Side effects & security: are secrets and resources safe?", "Tests & telemetry: would the evidence fail when the code is broken?"] },
  ],
  M01: [
    { id: "values-and-identities", eyebrow: "Start here", title: "Does a variable hold an object or a reference to it?", paragraphs: ["Primitive values are compared by value. An object variable points to an object's identity. Assigning it to another variable does not copy the object, and object spread copies only one level.", "This causes subtle AI-generated bugs: a factory reuses one default tags array, so tasks unexpectedly change each other."], code: zhLessons[2].sections[0].code, callout: { tone: "runtime", title: "Same shape does not mean separate data", body: "TypeScript describes shape; it does not copy objects or make them immutable." } },
    { id: "closures-and-this", eyebrow: "Where behavior comes from", title: "Closures remember surrounding variables; this depends on the call", paragraphs: ["A closure keeps access to variables around it. this is different: extracting a method and calling it another way can change this.", "Prefer explicit parameters and small closures in backend code. Use classes when you really need an object lifecycle."], bullets: ["Arrow functions capture the surrounding this", "A normal function gets this from the call site", "Shared mutable closure state needs a clear owner"] },
    { id: "modules-and-errors", eyebrow: "Module boundary", title: "Importing runs code, and throw can throw any value", paragraphs: ["An ES module runs its top-level code the first time it loads. Opening connections or timers during import makes tests depend on import order.", "JavaScript can throw a string, object, or null, so keep catch values as unknown and check them before reading message."], callout: { tone: "boundary", title: "Export a capability; do not secretly start it", body: "Prefer createXxx(), and let the entry point decide when to start and stop." } },
    { id: "project-p0-sync", eyebrow: "CodePilot P0", title: "Build one synchronous review task without a framework", paragraphs: ["Create ReviewJob, a factory, and a tiny CLI. Keeping the core independent from NestJS, databases, and model SDKs makes later changes safer."], bullets: ["Each job gets independent state", "The entry point parses arguments", "The CLI decides how errors are displayed"] },
  ],
  M02: [
    { id: "event-loop", eyebrow: "Start here", title: "Who continues the work after await?", paragraphs: ["An async function runs immediately until its first await. Code after await continues as a microtask; a timer callback waits for a later task. These are scheduled turns, not parallel threads.", "Draw the order before adding more await expressions."], callout: { tone: "runtime", title: "Draw a timeline first", body: "Separate synchronous code, microtasks, and external events when order matters." } },
    { id: "promise-errors", eyebrow: "Failure path", title: "An unawaited Promise does not send its error back automatically", paragraphs: ["If you forget await or return, an outer try/catch only covers the synchronous start. The later rejection may become unhandled.", "Do not hide it with catch(() => undefined). Decide who owns the error."], code: zhLessons[3].sections[1].code },
    { id: "async-iterable", eyebrow: "Incremental results", title: "A stream is a lifecycle, not just several callbacks", paragraphs: ["AsyncIterable lets a consumer pull values with for await...of and naturally represents completion, failure, and stopping early. Named events are clearer than raw strings."], bullets: ["Emit only one terminal event", "Do not emit more text after cancellation", "Release timers or connections in finally"] },
    { id: "abort-cleanup", eyebrow: "Reliability", title: "Cancellation must travel through the whole call chain", paragraphs: ["Pass AbortSignal into every operation that can wait. Timeouts and Ctrl+C may use different controllers but should become a clear domain reason.", "finally is the last line of defense for cleanup."], callout: { tone: "evidence", title: "Test silence after cancellation", body: "Prove that no later delta appears and that timers are cleared." } },
    { id: "project-p0-stream", eyebrow: "CodePilot P0", title: "Finish a cancellable mock streaming CLI", paragraphs: ["MockReviewProvider produces review text without contacting a model. The first Ctrl+C requests graceful cancellation; the second exits immediately."], bullets: ["The domain knows only ReviewStreamEvent and AbortSignal", "The provider emits events; the CLI displays them", "Tests use controlled time and no network"] },
  ],
};

const lessonText: Record<Lesson["id"], Pick<Lesson, "kicker" | "title" | "summary" | "outcomes" | "concepts">> = {
  P00: { kicker: "Zero-background preparation", title: "Read TypeScript for the First Time", summary: "No syntax dictionary. Build a tiny CodePilot task list by running, predicting, editing, and reading diagnostics.", outcomes: ["Explain how TypeScript, JavaScript, Node.js, and browsers relate", "Read variables, task objects, functions, and task states", "Use diagnostics and safely inspect unknown data"], concepts: ["essential syntax", "inference", "unions", "unknown", "type erasure"] },
  M00: { kicker: "Before we begin", title: "What Is the Human Responsible for After AI Writes the Code?", summary: "No red underline does not mean safe code. Learn a simple review order for real input and failures.", outcomes: ["Separate editor, type-check, build, runtime, and test evidence", "Review AI code with five TRUST questions", "Spot code that only looks safe"], concepts: ["evidence", "type erasure", "TRUST", "runtime input"] },
  M01: { kicker: "Runtime foundations", title: "JavaScript Is the Runtime", summary: "Use runnable examples to understand shared objects, remembered variables, and module loading.", outcomes: ["Predict references and shallow copies", "Explain closures, this, and module side effects", "Safely handle any thrown value"], concepts: ["values and references", "closures", "this", "ES modules", "unknown errors"] },
  M02: { kicker: "Async and streams", title: "Async Is a Protocol, Not Magic", summary: "Predict execution order, then build a mock review tool that streams, times out, and cancels.", outcomes: ["Explain synchronous work, microtasks, and timers", "Represent incremental events with AsyncIterable", "Carry AbortSignal through waiting operations"], concepts: ["event loop", "Promise", "AsyncIterable", "AbortSignal", "finally"] },
};

export const lessonsEn: Lesson[] = zhLessons.map((lesson) => ({ ...lesson, ...lessonText[lesson.id], sections: translatedSections[lesson.id] }));

export const labsEn = Object.fromEntries(Object.entries(zhLabs).map(([id, lab]) => [id, { ...lab }])) as typeof zhLabs;
Object.assign(labsEn["p00-type-task"], { title: "Playground 1 · Add a type to a task object", prompt: "Predict whether the title or undefined will print. Then describe the task fields and let the editor catch titel.", hint: "Create ReviewTask with a string title, number priority, and optional assignee.", expectedDiagnostics: "First task is implicitly any. After adding ReviewTask, the editor reports that titel does not exist and suggests title.", expectedOutput: "Before: [1] undefined; after: [1] Check login", initialCode: zhLabs["p00-type-task"].initialCode.replace("检查登录", "Check login"), solution: zhLabs["p00-type-task"].solution?.replace("检查登录", "Check login") });
Object.assign(labsEn["p00-task-status"], { title: "Playground 2 · Model task status with a union", prompt: "Predict blocked and typo, then replace any string with four allowed states.", hint: "Use todo | reviewing | done | blocked—like a menu with four choices.", expectedDiagnostics: "string accepts typo; the literal union rejects it.", expectedOutput: "Blocked; the invalid typo call is removed.", initialCode: zhLabs["p00-task-status"].initialCode.replace("已完成", "Done").replace("审查中", "Reviewing").replace("待处理", "To do"), solution: zhLabs["p00-task-status"].solution?.replace("已完成", "Done").replace("审查中", "Reviewing").replace("已阻塞", "Blocked").replace("待处理", "To do") });
Object.assign(labsEn["p00-unknown-input"], { title: "Playground 3 · Read unknown input safely", prompt: "Treat value as an unopened package. Prove it is an object with a string title before reading it.", hint: "Check object, non-null, title in value, then string.", expectedDiagnostics: "value is unknown, so value.title cannot be read yet.", expectedOutput: "SECURITY REVIEW" });
Object.assign(labsEn["m00-runtime-boundary"], { title: "Can a type assertion protect the runtime?", prompt: "Run the failure, remove the unsafe assertion, and validate the JSON shape.", hint: "Start JSON.parse output as unknown; check the object and its code field." });
Object.assign(labsEn["m01-shared-reference"], { title: "Why do two tasks share tags?", prompt: "Predict and run the output. Then give each task its own tags array.", hint: "Object spread copies one level; a nested array may still be shared." });
Object.assign(labsEn["m02-event-order"], { title: "What is await waiting for?", prompt: "Write down the A–E order, run it, then move await and explain the change.", hint: "Synchronous code runs first, Promise continuations are microtasks, and timers run later." });

export const lessonBySlugEn = new Map(lessonsEn.map((lesson) => [lesson.slug, lesson]));
export const labListEn = Object.values(labsEn) as Lab[];
export const searchItemsEn = lessonsEn.flatMap((lesson) => [
  { id: lesson.id, title: `${lesson.id} · ${lesson.title}`, description: lesson.summary, href: `/lesson/${lesson.slug}`, keywords: [...lesson.concepts, ...lesson.outcomes].join(" "), kind: "LESSON" },
  ...lesson.sections.map((section) => ({ id: `${lesson.id}-${section.id}`, title: section.title, description: section.paragraphs[0], href: `/lesson/${lesson.slug}#${section.id}`, keywords: `${lesson.concepts.join(" ")} ${section.code ?? ""}`, kind: "CONCEPT" })),
]);
